#!/bin/bash

echo

if [ "$#" -lt 3 ] || [ "$#" -gt 4 ]; then
    echo "Usage: $0 [<path>/]<folder_name> <start_index> <end_index>"
    echo
    exit 1
fi

full_path_and_folder_name=$1
start_index=$2
end_index=$3

# Extract the folder name and path
folder_name=$(basename "$full_path_and_folder_name")
path=$(dirname "$full_path_and_folder_name")

if ! [[ "$start_index" =~ ^[0-9]+$ ]] || [ "$start_index" -le 0 ] ||
	! [[ "$end_index" =~ ^[0-9]+$ ]] || [ "$end_index" -le 0 ]; then
    echo "ERROR: Indices must be positive integers!"
    echo
    exit 1
fi

# Check if the end index is less than the start index
if [ "$end_index" -le "$start_index" ]; then
    echo "ERROR: Number of folders must be greater than one!"
    echo
    exit 1
fi

# If no path is specified, use the current directory as the default path
if [ -z "$path" ]; then
    path="."
fi

# Check if the target directory exists and is writable
if [ ! -d "$path" ] || [ ! -w "$path" ]; then
    echo "ERROR: Invalid or inaccessible target directory!"
    echo
    exit 1
fi

for ((i = start_index; i <= end_index; i++)); do
    new_folder="${path}/${folder_name} $i"
    mkdir -p "$new_folder"
    echo "| Created folder: \"$new_folder\""
done

echo
echo "|> Folders created successfully!"
echo
